SELECT 
    CAR.CAR_ID, 
    CAR.CAR_TYPE, 
    FLOOR(CAR.DAILY_FEE * 30 * (1 - PLAN.DISCOUNT_RATE/100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CAR 
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
    ON PLAN.CAR_TYPE = CAR.CAR_TYPE 
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY 
    ON CAR.CAR_ID = HISTORY.CAR_ID 
    AND (HISTORY.START_DATE <= '2022-11-30' AND HISTORY.END_DATE >= '2022-11-01')
WHERE 
    CAR.CAR_TYPE IN ('SUV', '세단') 
    AND HISTORY.HISTORY_ID IS NULL -- 2022년 11월 1일부터 11월 30일 사이에 대여되지 않은 자동차 필터링
    AND PLAN.DURATION_TYPE = '30일 이상'
HAVING 
    FEE >= 500000 
    AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    CAR.CAR_TYPE ASC, 
    CAR.CAR_ID DESC;