SELECT 
    EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) 
                                        FROM USER_INFO 
                                        WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PURCHASED_RATIO
FROM 
    ONLINE_SALE O
JOIN 
    USER_INFO U ON O.USER_ID = U.USER_ID
WHERE 
    TO_CHAR(U.JOINED, 'YYYY') = '2021'  -- 2021년에 가입한 회원 필터링
    AND EXTRACT(YEAR FROM O.SALES_DATE) = 2022  -- 2022년에 발생한 구매 내역
GROUP BY 
    EXTRACT(YEAR FROM O.SALES_DATE), 
    EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY 
    YEAR ASC, MONTH ASC;