-- 코드를 입력하세요

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P 
JOIN FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE 
    O.PRODUCE_DATE >= TO_DATE('2022-05-01', 'YYYY-MM-DD') 
    AND O.PRODUCE_DATE < TO_DATE('2022-06-01', 'YYYY-MM-DD')
GROUP BY 
    P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
ORDER BY 
    TOTAL_SALES DESC, 
    PRODUCT_ID ASC;