-- 코드를 입력하세요

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P 
LEFT JOIN FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE 
    TO_CHAR(O.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY 
    P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
ORDER BY 
    TOTAL_SALES DESC, 
    PRODUCT_ID ASC;

